### PR TITLE
New web worker sample

### PR DESCRIPTION
**Pull request by davidchesnut**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                             |
| New sample?     | yes                              |
| Related issues? | -- |

## What's in this Pull Request?

Shows how to use web workers in custom functions.

### CODE REVIEW

**Comment by aafvstam** [comment]
The localhost version was not working for me. Also the readme needs some clarification and the local manifest is not completely right. I already prepared local code changes but have to bring them over to my fork before I can bring in the PR. Will follow up soon with my changes.

**Comment by davidchesnut** [comment]
@aafvstam, I merged your PR, and made updates to the manifest for online and localhost, so all should work correctly now. The online version won't work until this is in the master branch (so that the GitHub io pages are there.) Thanks!

**Review by aafvstam — APPROVED** [review]
The certificate part (openssl) to run with a valid certificate might need some more information but that can be adopted later on while finetuning. The example worked for me using the localhost (as you indicated the public version needs updating before getting that to work). I'll check that when that is in place.

**Comment by davidchesnut** [comment]
@aafvstam thanks for reviewing! We really appreciate it!

**Pull request merged**
