### PR TITLE
Upgrade MSAL.js to v2

### PR DESCRIPTION
**Pull request by jasonnutter**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                                |
| New sample?     | no                                |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

Hello! Jason from the MSAL.js team. This PR upgrades the Office Addin MS Graph React sample to use MSAL Browser, our new library which switches from the Implicit Flow to the Auth Code Flow w/ PKCE for SPAs. One notable advantage of upgrading to MSAL Browser is that is it should mitigate [problems caused by the Edge webview truncating long URLs](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2726). 

I have tested this with my own MSA account (my MSFT corp account needs admin permissions for the scopes used).

## Guidance

One change I cannot make myself is that the redirect URIs for `fc19440a-334e-471e-af53-a1c1f53c9226` need to be updated to the "Single Page Application" type. This type is backwards compatible with the Implicit Flow, so it would not break anyone using that client ID with the Implicit Flow (e.g. other samples, old versions of this sample).

PR template instructions to make this PR against `dev`, however, this sample does not exist in the `dev` branch. 

This sample is fantastic, thanks for putting it together!

### CODE REVIEW

**Comment by davidchesnut** [comment]
Hi @jasonnutter, thanks for this update! I'll take a look. Also invited @aafvstam in case he is interested in reviewing.

**Review by aafvstam — APPROVED** [review]
Worked for me!



I did make the mistake not to add the Redirect URI in the SPA section, instead added it to the Web section that surfaced by default. Might consider to make this flashing bold in the readme 😉

image

**Comment by aafvstam** [comment]
BTW, installing the npm packages in this demo will give a whole lot of security warnings.
Would be good to update a lot of the packages once this PR is pushed into master and create another PR for that to avoid fixing too much in one PR

**Comment by jasonnutter** [comment]
> Worked for me!
> 
> 
> 
> I did make the mistake not to add the Redirect URI in the SPA section, instead added it to the Web section that surfaced by default. Might consider to make this flashing bold in the readme 😉
> 
> image

That is fair feedback. cc: @hamiltonha

**Comment by davidchesnut** [comment]
This looks great! Merging it in.

**Pull request merged**
