### PR TITLE
Add contextual tabs sample

### PR DESCRIPTION
**Pull request by davidchesnut**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     | yes                              |
| Related issues? | NA |

## What's in this Pull Request?

Adding a new sample showing how to create and manage contextual tabs. Related to [Create custom contextual tabs in Office Add-ins (preview)](https://docs.microsoft.com/office/dev/add-ins/design/contextual-tabs)

### CODE REVIEW

**Review by aafvstam — CHANGES_REQUESTED** [review]
I have two findings:
- The projects fails on the first instance of npm run start. For some reason it does work when you run 'npm run start'  **again** (keep the first instance running). I found this by coincidence as I thought maybe it was caused by the incorrect webview. When testing I forgot to close the first failing instance and then magic happened to make it work in the second instance.
- The icons "https://osf-agave/AppCommands/RibbonAPITest/images/TaskPanes.32x32x32.png" are not loading as they don't exist or are unreachable this will cause an error in loading the taskpane.

Note that you need to fix the second issue first otherwise the first bullet will also fail.

So first the icons should be fixed by changing them to the local assets:
https://localhost:3000/assets/icon-16.png (and 32/80 pngs) 
next would be finding why the first instance doesn't show anything in the taskpane
not sure how to debug this, maybe you can give some pointers on how to do this.

**Comment by aafvstam** [comment]
BTW I have recorded all of this so you can check back if you want to, will add the URL for the Live Coding session here when it has been rendered by YouTube.

**Comment by aafvstam** [comment]
Here's the recording showing that the first run gives an empty TaskPane while the second instance is working:
https://youtu.be/9Fy4yf0JP3E?t=7876

**Comment by davidchesnut** [comment]
Thanks @aafvstam I will take a look!

**Comment by davidchesnut** [comment]
@aafvstam looks like sometimes on first sideload, the task pane doesn't load properly, so we're looking into this issue. I added a note to the readme to indicate to start a second instance if it happens. I also double-checked and there are no references to any images outside of localhost, so that should be fixed. I'm going to merge now. Thanks for the help!

**Pull request merged**
