### PR TITLE
dependency fix, and make readme clearer

### LINKED ISSUE #64: Debug error with ASP.NET React sample
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

I downloaded the sample and followed the instructions but something went wrong. Excel can't see the add-in. I named the project React1 Here are various steps...
React1 Warnings:
3>  npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
3>  npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
3>  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
3>  npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
\Office.ASP.NETCoreReactAddins\excel-js\ClientApp\node_modules\webpack-dev-server\node_modules\fsevents\node_modules\yallist' -> 'C:\vba\PnP-OfficeAddins-master\Samples\Office.ASP.NETCoreReactAddins\excel-js\ClientApp\node_modules\webpack-dev-server\node_modules\fsevents\node_modules\.yallist.DELETE'
3>
3>  added 1644 packages from 846 contributors and audited 919705 packages in 410.089s
3>  found 0 vulnerabilities
3>
3>Target CleanupEmptyRefsFolder:
3>  Directory "C:\vba\PnP-OfficeAddins-master\Samples\Office.ASP.NETCoreReactAddins\excel-js\bin\Debug\netcoreapp2.2\refs" doesn't exist. Skipping.
3>
3>Build succeeded.
3>    0 Warning(s)
3>    0 Error(s)
3>
3>Time Elapsed 00:07:17.54
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Note: Warnings seem to have been resolved.
Step 7: Properties/Application/Assembly name: = React1 (there is no Web Project property)
Note: only .NET 4.5.2 through 4.8 are available. This doesn't look right.
What happened to Net Core 2.2 Runtime (individual component)?

Step 8. In the Solution Explorer opened the manifest.xml file under the Office Add-in project (the project only contains a manifest file). 
Copy and save the <ID> that has the GUID for your project.
Note: What to do with it?
<Id>6e00caac-8450-4ca5-b019-b5c6ac08cafa</Id>
Step 9. Copied the contents of the manifest.xml file in the ASP .NET Core project 
and replaced all of the contents in the manifest file in the Web Add-in project (i.e. React1-Manifest.xml) with it.
Debug:
Upon Excel Launch:
ADD-IN Error: A problem occurred while trying to reach add-in.

My solution & project locations look like this:
ASP.NET Core_React_JavaScript.csproj
C:\...\PnP-OfficeAddins-master\Samples\OfficeASP.NETCoreReactAddins\excel-js\ASP.NET_Core_React_Javascript.csproj
React1.sln
C:\Users\Martin\source\repos\React1

I have ASP.NET Core 2.2 loaded as an extension. It bothers me that it doesn't show up as a selection
in the properties/application/frameworks.
Also, could there be an issue with the Web Project property? Don't see it anywhere.
Thanks

### PR DESCRIPTION
**Pull request by davidchesnut**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | Yes                               |
| New feature?    | no                               |
| New sample?     | no                                |
| Related issues? | fixes #64 |

## What's in this Pull Request?

- Fixes an issue that was occurring with React scripts (see https://github.com/facebook/create-react-app/issues/8680). 
- Adds images to readme to make the steps clearer.
- Adds missing step to readme to paste in your original GUID in the manifest.

### CODE REVIEW

**Comment by aafvstam** [comment]
As already mentioned in my previous comments, the dupe babel-eslint should go into devDependencies only (did a quick check online to find this one asking the same thing: https://stackoverflow.com/questions/40143357/do-you-put-babel-and-webpack-in-devdependencies-or-dependencies).

Maarten

**Comment by davidchesnut** [comment]
@aafvstam and @John-Hart I removed the duplicate babel-eslint. I also noticed that the images were not loading, so I moved them into the public folder. Would be great for someone to double-check that I did this correctly. Thanks!

**Comment by aafvstam** [comment]
> @aafvstam and @John-Hart I removed the duplicate babel-eslint. I also noticed that the images were not loading, so I moved them into the public folder. Looks like the react dom router was interfering when they were in assets folder. Would be great for someone to double-check that I did this correctly. Thanks!

I'll have a look at this (and your other changes) upcoming Thursday in my Twitch session 👍

**Comment by davidchesnut** [comment]
@aafvstam that's cool! Is it Thursday 1pm PST? I'll check it out! Thanks!

**Comment by aafvstam** [comment]
Checked and all working ... pull it in!

**Comment by aafvstam** [comment]
Can someone pull this in, it is waiting for approval for the second reviewer for some time and I'm not allowed to approve. That gives me the option to proceed preparing it for .NET Core 5 RC ;-)

**Comment by AlexJerabek** [comment]
There you go, @aafvstam! Thanks for testing it out. Curious that you couldn't change your approval status, If that happens on another PR, we should probably dig into the GitHub settings.

**Pull request merged**
