### PR TITLE
shared runtime ribbon sample

### PR DESCRIPTION
**Pull request by davidchesnut**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | yes                             |
| New sample?     | yes                              |
| Related issues? | - |

## What's in this Pull Request?

This sample shows how to use the new Ribbon APIs to enable/disable buttons, show or hide the task pane, run code when the task is closed, and set your add-in to run on document open.

### CODE REVIEW

**Comment by Rick-Kirkham** [comment]
Not having much luck. When I sideload, the add-in seems to be install (The Contoso tab appears on the ribbon); but I get the following error near the bottom of the Excel window:

InstallError1

If I close Excel and re-sideload, I get this variant version of the error:
InstallError2

Regardless of which of those errors I get, If I press either the **Open task pane** or the **Connect service** I get the following message at the bottom of the Excel window. But nothing else happens and this error never goes away. 
InstallError3

**Comment by davidchesnut** [comment]
@Rick-Kirkham the project was not configured to provide the CORS headers for custom functions. I fixed that if you want to give it another try. Thanks!

**Comment by mscharlock** [comment]
I tried this with the latest changes, works for me! :)

**Comment by Rick-Kirkham** [comment]
@mscharlock @davidchesnut  OK. Since Michelle has it working, It must be essentially sound, so I'll make it only a low priority for me to try again. If others have problems, they'll raise issues.

**Comment by davidchesnut** [comment]
Thanks everyone for the help reviewing!

**Pull request merged**
